[workspace]
members = ["crates/esr_core", "crates/esr_node", "crates/esr_server", "crates/esr_video"]
resolver = "2"

[package]
name = "esr_tp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "node"
path = "src/node.rs"

[[bin]]
name = "server"
path = "src/server_launcher.rs"

[[bin]]
name = "client"
path = "src/client_launcher.rs"

[[bin]]
name = "rp"
path = "src/rp_launcher.rs"

[lib]
name = "esr_lib"
path = "src/lib.rs"

[workspace.dependencies]
esr_core.path = "crates/esr_core"
esr_server.path = "crates/esr_server"
esr_video.path = "crates/esr_video"

serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
rand = "0.8.6"
thiserror = "1.0.50"
bincode = "1.3.3"
clap = { version = "4.4.6", features = ["derive"] }

[dependencies]
bincode.workspace = true
clap.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

gtk = "0.18.1"

esr_core.path = "crates/esr_core"
esr_node.path = "crates/esr_node"
esr_server.path = "crates/esr_server"
esr_video.path = "crates/esr_video"
